name: Laboratorio Final DevSecOps

on:
  push: 
    branches: ["**"]          # se ejecuta en cada commit a cualquier rama

permissions:
  contents: read
  security-events: write
  pull-requests: read

jobs:
  anlisis-SAST:
    runs-on : ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        #run: echo "Ejecutando checkout para analizar código"

      - name: analisis de Codigo SAST
        id: AnalisisSAST
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN:  ${{ secrets.SONAR_TOKEN }}
        #with:
          #args: >
            #-Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            #-Dsonar.organization=${{ secrets.SONAR_ORG }}
            #-Dsonar.javascript.node.maxspace=4096
            #-Dsonar.qualitygate.wait=true
        #run: echo "status=ok" >> "$GITHUB_OUTPUT"
           
      - name: Analisis SAST OK
        if: steps.AnalisisSAST.outputs.status == 'ok'
        run:
          echo "Analisis SAST OK - TEST"
          
      - name: Analisis SAST NOK
        if: steps.AnalisisSAST.outputs.status != 'ok'
        run:
          echo "Analisis SAST NOK - TEST"


  anlisis-SCA:
    runs-on : ubuntu-latest
    #needs: [AnalisisSAST]  # este job corre después de AnalisisSAST
    steps:
      - name: analisis de Codigo SCA
        run:
          echo "analisis de Codigo SCA"
          
  Build-Docker:
    runs-on : ubuntu-latest
    steps:
      - name: Build Docker
        run:
          echo "Build Docker"
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)


  Image-Security:
    runs-on : ubuntu-latest
    steps:
      - name: Image Security
        run:
          echo "Image Security"

#1. Clonación del repositorio.
#2. Ejecutar SAST -> Usar SonarCloud o herramienta similar.
#3. Ejecutar SCA ->Usar Dependency Check o similar.
#4. Construcción de la Imagen Docker.
#5. Image Security -> Usar Trivy o similar.
  
